#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ./Tracker.Db/ ./Tracker.Db/
COPY ./SharedLib/ ./SharedLib/
COPY ./loco_contracts/ ./loco_contracts/

WORKDIR "/src/Tracker.Db"
RUN dotnet restore "Tracker.Db.csproj"
RUN dotnet build "Tracker.Db.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Tracker.Db.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tracker.Db.dll"]