#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ./Management.Db/  ./Management.Db/
COPY ./SharedLib/ ./SharedLib/
COPY ./loco_contracts/ ./loco_contracts/

WORKDIR "/src/Management.Db"
RUN dotnet restore "Management.Db.csproj"
RUN dotnet build "Management.Db.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Management.Db.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Management.Db.dll"]