#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ./Notification.Db/ ./Notification.Db/
COPY ./SharedLib/ ./SharedLib/
COPY ./loco_contracts/ ./loco_contracts/

WORKDIR "/src/Notification.Db"
RUN dotnet restore "Notification.Db.csproj"
RUN dotnet build "Notification.Db.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Notification.Db.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Notification.Db.dll"]